# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ping-app
  template:
    metadata:
      labels:
        app: ping-app
    spec:
      containers:
      - name: ping-app
        image: k-ping-app:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5550
        resources:
          limits:
            cpu: "0.5"
            memory: "512Mi"
          requests:
            cpu: "0.1"
            memory: "128Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: ping-service
spec:
  selector:
    app: ping-app
  ports:
  - protocol: TCP
    port: 5550
    targetPort: 5550
  type: ClusterIP
